theme: minima
title: Welcome to the CS World
author: Ali Al-Azadi
email: ali145@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Learn about how to succeed a student who is new to CS. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: seattle145 # DO NOT include the @ character, or else the build will fail!
github_username:  seattle145 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
